name: Waka Readme

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_DAYS_OF_WEEK: "FALSE"
          SHOW_LINES_OF_CODE: "FALSE"
          SHOW_PROFILE_VIEWS: "FALSE"
          SHOW_TOTAL_CODE_TIME: "FALSE"
          SHOW_COMMIT: "FALSE"
          SHOW_LANGUAGE_PER_REPO: "FALSE"
          SHOW_SHORT_INFO: "FALSE"
          SHOW_EDITORS: "FALSE"
          SHOW_TIMEZONE: "FALSE"
          SHOW_LOC_CHART: "FALSE"
